### ISSUE TITLE
sudo

### ISSUE THREAD

**Issue by terwey** [Graylog2/graylog2-ansible-role#8]
Hey,

this role assumes the usage of sudo, which results in ```stderr: /bin/sh: 1: sudo: not found``` if sudo is not installed.

It does it here https://github.com/Graylog2/graylog2-ansible-role/blob/cbf9152d2bb0f6e47d46cc599f421b2b2c6cf7b6/tasks/prepare.yml#L22

Debian usually does not have sudo

**Comment by mariussturm** [comment]
Fixed in latest release
